version: 0.0
os: linux
files:
  - source: / 
    destination: /opt/blackpearl
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/prepare_deployment.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_filename.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidationService:
    - location: scripts/validate_deployment.sh
      timeout: 300
      runas: root
